# Redirect bellinitia.com to bellinitia.me
[[redirects]]
  from = "https://bellinitia.com/*"
  to = "https://bellinitia.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://bellinitia.com/*"
  to = "https://bellinitia.me/:splat"
  status = 301
  force = true

# Redirect www subdomain as well
[[redirects]]
  from = "https://www.bellinitia.com/*"
  to = "https://bellinitia.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.bellinitia.com/*"
  to = "https://bellinitia.me/:splat"
  status = 301
  force = true


### ZOOM REDIRECT - Redirect to the current Zoom meeting link
[[redirects]]
  from = "/meet"
  to = "https://ut-ee.zoom.us/j/9151500129?pwd=WmUvWFc4c3EwdjJoVVptM2FqaDRpQT09"
  status = 302 # Temporary Redirect